auto-save:
  enable: true
  timer(s): 1200
  save-when-unload: true
auto-backup:
  enable: true
  timer(s): 1200
  backup-when-unload: true
backup:
  path: 'backups'

default-language: 'zh_cn'
date-time-zone: 'Asia/Shanghai'