name: IronSaver
main: bluescreen9.minecraft.bukkit.ironsaver.Main
version: 0.0.2
description: 'a simple bukkit plugin for world saving'
commands:
  ironsave: 
    description: 'The command to save or backup world'